# Any snapshot for GHC >= 8.4 should work, we pick a recent stable one:
# (recent as of 2023-10-24)
resolver: lts-21.22

# See https://www.stackage.org/ "Latest releases per GHC version"
# for alternatives.
